# Run `conda-env create -f environment.yml`
name: fixit-app
channels:
  - conda-forge

dependencies:
  - python=3.6
  - flask
  - folium
  - geopandas
  - ipython
  - networkx
  - numba
  - numpy
  - osmnx
  - pandas
  - scipy

