# Run `conda-env create -f environment.yml`
name: fixit-app
channels:
  - conda-forge

dependencies:
  - python=3.6
  - bokeh
  - dill
  - flask
  - folium
  - geopandas
  - ipython
  - networkx
  - numba
  - osmnx
  - palettable
  - pandas
  - pip
  - rasterio
  - scikit-learn
  - seaborn
  - xlrd
  - xlsxwriter
